# Generated by Django 3.2.12 on 2022-09-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField(null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('DOB', models.DateField()),
                ('Img', models.ImageField(null=True, upload_to='Pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tamil', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('S_Science', models.IntegerField()),
                ('Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='re24_app.student')),
            ],
        ),
    ]
