# Generated by Django 3.2.12 on 2022-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re24_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='English',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='Maths',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='S_Science',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='Science',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='Tamil',
        ),
        migrations.AddField(
            model_name='mark',
            name='mrk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='sub',
            field=models.CharField(default='null = True', max_length=50),
            preserve_default=False,
        ),
    ]
