# Generated by Django 3.2.12 on 2022-10-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re24_app', '0003_rename_id_mark_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='student_id',
            new_name='student',
        ),
    ]
