# Generated by Django 3.2.12 on 2022-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re24_app', '0006_auto_20221004_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
