# Generated by Django 3.2.12 on 2022-10-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re24_app', '0007_auto_20221004_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='creator',
            field=models.CharField(default='null = True', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='updater',
            field=models.CharField(default='null = Yrue', max_length=50),
            preserve_default=False,
        ),
    ]
